---
- name: Install GitHub Actions Runner
  hosts: all
  user: ansible
  become: yes

  tasks:
  - name: Create user Runner
    ansible.builtin.include_role:
      name: ansible-user_management
    vars:
      user_management:
      - name: Runner 
        comment: Runner
        shell: /bin/bash
        groups:
          - sudo
        create_home: no

  - name: Install github runner
    ansible.builtin.include_role:
      name: ansible-github_actions_runner
    vars:
      github_account: t-frog-says-jump
      github_repo: hello-most

  - name: Run copy shell sc
    ansible.builtin.script: ./copy.sh

  - name: Create user Runner
    ansible.builtin.include_role:
      name: community.zabbix.zabbix_agent
    vars:
      zabbix_agent_server: 192.168.33.30
      zabbix_agent_serveractive: 192.168.33.30
      zabbix_api_server_host: zabbix.example.com
      zabbix_api_login_user: Admin
      zabbix_api_login_pass: zabbix
      zabbix_api_create_hostgroup: true
      zabbix_api_create_hosts: true
      zabbix_agent_host_state: present
      zabbix_host_groups:
        - Linux Servers
      zabbix_agent_link_templates:
        - Template OS Linux
        - Apache APP Template
      zabbix_agent_macros:
        - macro_key: apache_type
          macro_value: reverse_proxy
          macro_type: text
      zabbix_agent_tags:
        - tag: environment
          value: production
            
  - name: "Flush handlers"
    ansible.builtin.meta: flush_handlers