Vagrant.configure("2") do |config|

  config.vm.box = "gusztavvargadr/ubuntu-server-2204-lts"
  config.vm.box_version = "2204.0.2505"

  (1..2).each do |i|
    config.vm.define "ubuntu-server-#{i}" do |node|
      node.vm.network "private_network", ip: "192.168.0.10#{i}"
      
      node.vm.provider "virtualbox" do |virtualbox|
        virtualbox.gui = true
        virtualbox.linked_clone = false
        virtualbox.memory = "4096"
        virtualbox.cpus=2
      end

      node.vm.box_check_update = false
    end
  end
end
